export const DATA = {
  Email: 'email',
  Password: 'password',
  Form: 'signup-form',
  Login: 'Login',
  Submit: 'submit',
  ConfirmPassword: 'confirmPassword',
  FormContainer: 'signup-container',
  OrDivider: 'or-divider',
  TypeButton: 'button',
  GoggleButton: 'google-btn',
  SignUp: 'Sign Up',
  DontHave: "Don't have an account?",
  AlreadyHave: 'Already have an account?',
  HeaderContainer: 'header-container',
  SearchContainer: 'search-container',
  TypeText: 'text',
  HeaderChildren: 'header-children',
  Or: 'OR',
  Logo: 'Logo',
  InvalidEmail: 'Invalid email',
  PasswordLength: 'Password must be at least 6 characters',
  EmailRequired: 'Email is required',
  PasswordRequired: 'Password is required',
  PasswordMatching: 'Paswords must match',
  ConfirmPasswordRequired: 'Confirm Password is required',
};
